name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ qwe, rty, uio ]
    steps:
      - name: Checkout (including submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create file
        run: |
          mkdir datadir
          cd datadir
          echo "${{ matrix.platform }} https://${{ matrix.platform }}.com" > ${{ matrix.platform }}.txt
      - uses: actions/upload-artifact@v3
        with:
          path: datadir/${{ matrix.platform }}.txt
  second: 
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Download file
        uses: actions/download-artifact@master
        with:
          path: datadir
      - name: Format
        run: |
          find .
        
